#+OPTIONS: title:nil author:nil date:nil toc:nil num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [letterpaper,11pt]
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{latexsym}
#+LATEX_HEADER: \usepackage[empty]{fullpage}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage{marvosym}
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{verbatim}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \hypersetup{hidelinks}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{hyphenat}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{}
#+LATEX_HEADER: \fancyfoot{}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER: \addtolength{\oddsidemargin}{-0.5in}
#+LATEX_HEADER: \addtolength{\evensidemargin}{-0.5in}
#+LATEX_HEADER: \addtolength{\textwidth}{1in}
#+LATEX_HEADER: \addtolength{\topmargin}{-.5in}
#+LATEX_HEADER: \addtolength{\textheight}{1.0in}
#+LATEX_HEADER: \setlength{\footskip}{8pt}
#+LATEX_HEADER: \urlstyle{same}
#+LATEX_HEADER: \raggedbottom
#+LATEX_HEADER: \raggedright
#+LATEX_HEADER: \setlength{\tabcolsep}{0in}
#+LATEX_HEADER: \titleformat{\section}{\vspace{-4pt}\scshape\raggedright\large}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]
#+LATEX_HEADER: \newcommand{\resumeItem}[1]{\item\small{{#1 \vspace{-2pt}}}}
#+LATEX_HEADER: \newcommand{\resumeSubheading}[4]{\vspace{-2pt}\item\begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}\textbf{#1} & #2 \\\textit{\small#3} & \textit{\small #4} \\\end{tabular*}\vspace{-7pt}}
#+LATEX_HEADER: \newcommand{\resumeSubSubheading}[2]{\vspace{-2pt}\item\begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}\textit{\small#1} & \textit{\small #2} \\\end{tabular*}\vspace{-7pt}}
#+LATEX_HEADER: \newcommand{\resumeEducationHeading}[6]{\vspace{-2pt}\item\begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}\textbf{#1} & #2 \\\textit{\small#3} & \textit{\small #4} \\\textit{\small#5} & \textit{\small #6} \\\end{tabular*}\vspace{-5pt}}
#+LATEX_HEADER: \newcommand{\resumeProjectHeading}[2]{\vspace{-2pt}\item\begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}\small#1 & #2 \\\end{tabular*}\vspace{-7pt}}
#+LATEX_HEADER: \newcommand{\resumeOrganizationHeading}[4]{\vspace{-2pt}\item\begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}\textbf{#1} & \textit{\small #2} \\\textit{\small#3}\end{tabular*}\vspace{-7pt}}
#+LATEX_HEADER: \newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}
#+LATEX_HEADER: \renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}
#+LATEX_HEADER: \newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
#+LATEX_HEADER: \newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
#+LATEX_HEADER: \newcommand{\resumeItemListStart}{\begin{itemize}}
#+LATEX_HEADER: \newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

#+begin_export latex
\begin{center}
    \textbf{\Huge \scshape Aaron He} \\ \vspace{3pt}
    \small
    \href{mailto:aaron.he@student.unsw.edu.au}{aaron.he@student.unsw.edu.au}
    $|$
    \href{https://github.com/AaronHnoraA}{github.com/AaronHnoraA}
    $|$
    \href{https://aaronhnoraa.github.io/}{aaronhnoraa.github.io}
    $|$
    Sydney, Australia
\end{center}
#+end_export

* Education
#+begin_export latex
\vspace{3pt}
\resumeSubHeadingListStart

  \resumeEducationHeading
    {University of New South Wales (UNSW)}{Sydney, Australia}
    {B.Sc. in Mathematics, UNSW 3956; expected graduation: Term 3, 2028 (Honours)}{Commenced: Term 3, 2024}
    {Planned transfer to B.Sc. in Computer Science, UNSW 3779; WAM: \textbf{85}}{}
    \resumeSubHeadingListStart
    \small{\item{
      \textbf{Talented Students Program (TSP):} admitted in 2025. \href{https://www.unsw.edu.au/science/student-life-resources/student-opportunities/talented-students-program}{Program link}.}}
    \resumeSubHeadingListEnd

\resumeSubHeadingListEnd
#+end_export

* Research Interests
#+begin_export latex
\vspace{2pt}
\resumeSubHeadingListStart
  \small{\item{
    \textbf{Quantum computing:} quantum states, observables, density operators, measurement, and the linear-algebraic foundations behind them. \\ \vspace{3pt}
    \textbf{Mathematics:} linear algebra, inner product spaces, Hilbert spaces, Hermitian operators, and related algebraic structure. \\ \vspace{3pt}
    \textbf{Theoretical computer science:} long-term interest in complexity theory, algorithms, and communication complexity. \\ \vspace{3pt}
  }}
\resumeSubHeadingListEnd
#+end_export

* Research Experience
#+begin_export latex
\vspace{3pt}
\resumeSubHeadingListStart

  \resumeSubheading
    {Talented Students Program, UNSW}{Sydney, Australia}
    {Academic Reading with \href{https://www.unsw.edu.au/staff/quoc-le-gia}{Quoc Le Gia}}{Term 1, 2025}
    \resumeItemListStart
      \resumeItem{Undertook academic reading in large language models under the Talented Students Program.}
    \resumeItemListEnd

  \resumeSubheading
    {Independent Study, UNSW}{Sydney, Australia}
    {Quantum Computing and Theoretical Computer Science with \href{https://www.unsw.edu.au/staff/youming-qiao}{Youming Qiao}}{Term 2, 2025 -- Present}
    \resumeItemListStart
      \resumeItem{Studying quantum computing and theoretical computer science through directed reading and regular supervision.}
      \resumeItem{Currently writing a paper on graph isomorphism and tensor isomorphism problems.}
    \resumeItemListEnd

\resumeSubHeadingListEnd
#+end_export

* Academic Notes
#+begin_export latex
\vspace{2pt}
\resumeSubHeadingListStart
  \resumeProjectHeading
    {\textbf{Personal Homepage and Open Notebook} $|$ \emph{\href{https://aaronhnoraa.github.io/}{website}}}{2026}
    \resumeItemListStart
      \resumeItem{Maintains a public set of mathematics and quantum computing notes, including expository writing on Hilbert spaces, quantum states, observables, density operators, and related linear algebra.}
    \resumeItemListEnd

  \resumeProjectHeading
    {\textbf{Selected Topics Covered}}{}
    \resumeItemListStart
      \resumeItem{Quantum states; observable and expectation; density operators; Hilbert spaces; inner product spaces; Hermitian matrices.}
    \resumeItemListEnd

\resumeSubHeadingListEnd
#+end_export
