import { describe, expect, test } from "@voidzero-dev/vite-plus-test";
import {
  buildLeanSplice,
  leanOffsetToNote,
  leanOffsetToPosition,
  leanPathForNote,
  leanPositionToOffset,
  noteOffsetToLean,
} from "../src/lean-splice.ts";

// ---------------------------------------------------------------------------
// leanPathForNote
// ---------------------------------------------------------------------------

describe("leanPathForNote", () => {
  test("replaces .md with .lean under .lean/", () => {
    expect(leanPathForNote("/root/notes/algebra/groups.md", "/root/notes"))
      .toBe("/root/notes/.lean/algebra/groups.lean");
  });

  test("works with trailing slash on root", () => {
    expect(leanPathForNote("/root/notes/foo.md", "/root/notes/"))
      .toBe("/root/notes/.lean/foo.lean");
  });

  test("handles note at root", () => {
    expect(leanPathForNote("/root/notes/test.md", "/root/notes"))
      .toBe("/root/notes/.lean/test.lean");
  });
});

// ---------------------------------------------------------------------------
// buildLeanSplice — null for no blocks
// ---------------------------------------------------------------------------

describe("buildLeanSplice — no lean4 blocks", () => {
  test("returns null for pure text note", () => {
    expect(buildLeanSplice("/r/foo.md", "# Hello\n\nJust text.", "/r")).toBeNull();
  });

  test("returns null for other org-env blocks", () => {
    const md = "#+begin theorem\nsome math\n#+end theorem\n";
    expect(buildLeanSplice("/r/foo.md", md, "/r")).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// buildLeanSplice — basic structure
// ---------------------------------------------------------------------------

const BASIC_MD = `# Groups

Some prose.

#+begin lean4
import Mathlib.Tactic
variable (G : Type*) [Group G]
#+end lean4

More prose.

#+begin lean4 ProofCell
example (a b : G) : a * b * b⁻¹ = a := by simp
#eval 1 + 1
#+end lean4
`;

describe("buildLeanSplice — basic", () => {
  const splice = buildLeanSplice("/notes/groups.md", BASIC_MD, "/notes")!;

  test("is non-null", () => expect(splice).not.toBeNull());

  test("leanPath is correct", () => {
    expect(splice.leanPath).toBe("/notes/.lean/groups.lean");
  });

  test("has two blocks", () => {
    expect(splice.blocks).toHaveLength(2);
  });

  test("block titles", () => {
    expect(splice.blocks[0].title).toBe("");
    expect(splice.blocks[1].title).toBe("ProofCell");
  });

  test("lean text contains autogen header", () => {
    expect(splice.leanText).toContain("-- AUTOGENERATED FROM /notes/groups.md");
  });

  test("lean text contains cell markers", () => {
    expect(splice.leanText).toContain("-- @cell 0 begin");
    expect(splice.leanText).toContain("-- @cell 0 end");
    expect(splice.leanText).toContain("-- @cell 1 begin");
    expect(splice.leanText).toContain("-- @cell 1 end");
  });

  test("lean text contains block bodies", () => {
    expect(splice.leanText).toContain("import Mathlib.Tactic");
    expect(splice.leanText).toContain("example (a b : G)");
    expect(splice.leanText).toContain("#eval 1 + 1");
  });

  test("leanFrom/leanTo match actual text offsets", () => {
    for (const block of splice.blocks) {
      expect(splice.leanText.slice(block.leanFrom, block.leanTo)).toBe(
        BASIC_MD.slice(block.noteBodyFrom, block.noteBodyTo),
      );
    }
  });
});

// ---------------------------------------------------------------------------
// Offset mapping
// ---------------------------------------------------------------------------

describe("offset mapping", () => {
  const md = "#+begin lean4\ntheorem foo : 1 = 1 := rfl\n#eval 1\n#+end lean4\n";
  const splice = buildLeanSplice("/r/t.md", md, "/r")!;

  test("block body matches", () => {
    const body = md.slice(splice.blocks[0].noteBodyFrom, splice.blocks[0].noteBodyTo);
    expect(body).toBe("theorem foo : 1 = 1 := rfl\n#eval 1\n");
  });

  test("leanOffsetToNote round-trips for start of block", () => {
    const noteOff = leanOffsetToNote(splice, splice.blocks[0].leanFrom)!;
    expect(noteOff).toBe(splice.blocks[0].noteBodyFrom);
  });

  test("leanOffsetToNote round-trips for end of block", () => {
    const noteOff = leanOffsetToNote(splice, splice.blocks[0].leanTo)!;
    expect(noteOff).toBe(splice.blocks[0].noteBodyTo);
  });

  test("noteOffsetToLean round-trips", () => {
    const noteOff = splice.blocks[0].noteBodyFrom + 5;
    const leanOff = noteOffsetToLean(splice, noteOff)!;
    expect(leanOff).toBe(splice.blocks[0].leanFrom + 5);
    expect(leanOffsetToNote(splice, leanOff)).toBe(noteOff);
  });

  test("leanOffsetToNote returns null for header", () => {
    expect(leanOffsetToNote(splice, 0)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Position utilities
// ---------------------------------------------------------------------------

describe("position utilities", () => {
  const text = "line0\nline1\nline2\n";

  test("leanOffsetToPosition at start", () => {
    expect(leanOffsetToPosition(text, 0)).toEqual({ line: 0, character: 0 });
  });

  test("leanOffsetToPosition mid-first-line", () => {
    expect(leanOffsetToPosition(text, 3)).toEqual({ line: 0, character: 3 });
  });

  test("leanOffsetToPosition second line", () => {
    expect(leanOffsetToPosition(text, 6)).toEqual({ line: 1, character: 0 });
  });

  test("leanPositionToOffset round-trips", () => {
    expect(leanPositionToOffset(text, 1, 3)).toBe(9);
    expect(leanOffsetToPosition(text, 9)).toEqual({ line: 1, character: 3 });
  });
});

// ---------------------------------------------------------------------------
// Edge cases
// ---------------------------------------------------------------------------

describe("edge cases", () => {
  test("nested lean4 blocks are included in order", () => {
    const md = [
      "#+begin lean4",
      "outer",
      "#+begin lean4",
      "inner",
      "#+end lean4",
      "#+end lean4",
    ].join("\n") + "\n";
    // top-level scanner: outer block body includes the inner #+begin/end literally
    const splice = buildLeanSplice("/r/t.md", md, "/r")!;
    expect(splice.blocks).toHaveLength(1);
    const body = md.slice(splice.blocks[0].noteBodyFrom, splice.blocks[0].noteBodyTo);
    expect(body).toContain("outer");
    expect(body).toContain("inner");
  });

  test("unclosed block is skipped", () => {
    const md = "#+begin lean4\ncode\n";
    expect(buildLeanSplice("/r/t.md", md, "/r")).toBeNull();
  });

  test("case-insensitive begin/end", () => {
    const md = "#+BEGIN lean4\ncode\n#+END lean4\n";
    const splice = buildLeanSplice("/r/t.md", md, "/r")!;
    expect(splice.blocks).toHaveLength(1);
  });
});
