:PROPERTIES:
:ID:       20BE5DF6-29D8-4B26-AA52-BFD8AB02A02F
:END:
#+title: Hermitian Matrix
#+date: [2026-01-27 Tue]
#+filetags: :math:QC:concept:


* Hermitian Matrix

埃尔米特矩阵（英语：Hermitian matrix，又译作厄米特矩阵，厄米矩阵），也称自伴随矩阵，是共轭对称的方阵。埃尔米特矩阵中每一个第 \(i\) 行第 \(j\) 列的元素都与第 \(j\) 行第 \(i\) 列的元素的复共轭。例如$\begin{bmatrix}3&2+i\\2-i&1\end{bmatrix}$ 就是一个埃尔米特矩阵。

显然，埃尔米特矩阵主对角线上的元素都是实数，其特征值也是实数。对于实矩阵，如果它是对称矩阵，则它也满足埃尔米特矩阵的定义，即，实对称矩阵是埃尔米特矩阵的特例。

* 性质
- 若 $A$ 和 $B$ 是埃尔米特矩阵，那么它们的和 $A+B$ 也是埃尔米特矩阵；而只有在 $A$ 和 $B$ 满足交换性（即 $AB=BA$）时，它们的积才是埃尔米特矩阵。
- 可逆的埃尔米特矩阵 $A$ 的逆矩阵 $A^{-1}$ 仍然是埃尔米特矩阵。
- 如果 $A$ 是埃尔米特矩阵，对于正整数 $n$，$A^{n}$ 是埃尔米特矩阵。
- 方阵 $C$ 与其共轭转置的和 $C+C^{*}$ 是埃尔米特矩阵，方阵 $C$ 与其共轭转置的差 $C-C^{*}$ 是斜埃尔米特矩阵。
- 任意方阵 $C$ 都可以用一个埃尔米特矩阵 $A$ 与一个斜埃尔米特矩阵 $B$ 的和表示：
  \[ C=A+B \quad \text{with} \quad A=\frac{1}{2}(C+C^{*}) \quad \text{and} \quad B=\frac{1}{2}(C-C^{*}) \]
- 埃尔米特矩阵是正规矩阵，因此埃尔米特矩阵可被酉对角化，而且得到的对角阵的元素都是实数。这意味着埃尔米特矩阵的特征值都是实的，而且不同的特征值所对应的特征向量相互正交，因此可以在这些特征向量中找出一组 $\mathbb{C}^n$ 的正交基。
- $n$ -阶埃尔米特矩阵的元素构成维数为 $n^{2}$ 的实向量空间，因为主对角线上的元素有一个自由度，而主对角线之上的元素有两个自由度。
- 如果埃尔米特矩阵的特征值都是正数，那么这个矩阵是正定矩阵；若它们是非负的，则这个矩阵是半正定矩阵.

