/**
 * Lean 4 splice builder.
 *
 * Scans `#+begin lean4` … `#+end lean4` blocks from a markdown note,
 * concatenates their bodies into a single `.lean` file, and maintains a
 * bidirectional offset table between note positions and lean-file positions.
 *
 * This module has zero Node.js / CM6 imports so it works in browser, tests,
 * and server contexts alike.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface LeanBlockSlice {
  index: number;
  title: string;

  /** Start of block body in the note (character offset into mdText). */
  noteBodyFrom: number;
  /** End of block body in the note (exclusive). */
  noteBodyTo: number;

  /** Start of block body in the generated lean text. */
  leanFrom: number;
  /** End of block body in the generated lean text (exclusive). */
  leanTo: number;
}

export interface LeanSplice {
  notePath: string;
  leanPath: string;
  blocks: LeanBlockSlice[];
  /** Full content of the generated .lean file. */
  leanText: string;
}

// ---------------------------------------------------------------------------
// Scanner
// ---------------------------------------------------------------------------

interface RawLean4Block {
  bodyFrom: number;
  bodyTo: number;
  body: string;
  title: string;
}

/** Finds all #+begin lean4 … #+end lean4 blocks in order. Handles nesting. */
function scanLean4Blocks(mdText: string): RawLean4Block[] {
  const OPEN_RE = /^[ \t]*#\+begin[ \t]+lean4(?:[ \t]+([^\n]*))?[ \t]*$/i;
  const CLOSE_RE = /^[ \t]*#\+end[ \t]+lean4[ \t]*$/i;

  const results: RawLean4Block[] = [];
  const lines = mdText.split("\n");

  // precompute line start offsets
  const lineStart: number[] = new Array(lines.length);
  let off = 0;
  for (let k = 0; k < lines.length; k++) {
    lineStart[k] = off;
    off += lines[k].length + 1; // +1 for \n
  }

  let i = 0;
  while (i < lines.length) {
    const openMatch = OPEN_RE.exec(lines[i]);
    if (!openMatch) { i++; continue; }

    const title = (openMatch[1] ?? "").trim();
    const bodyFrom = lineStart[i] + lines[i].length + 1; // after opening line \n

    // find matching #+end lean4, tracking nesting depth
    let depth = 1;
    let j = i + 1;
    while (j < lines.length) {
      if (OPEN_RE.test(lines[j])) {
        depth++;
      } else if (CLOSE_RE.test(lines[j])) {
        depth--;
        if (depth === 0) break;
      }
      j++;
    }

    if (depth !== 0) { i++; continue; } // unclosed block — skip

    const bodyTo = lineStart[j]; // closing #+end line starts here
    results.push({ bodyFrom, bodyTo, body: mdText.slice(bodyFrom, bodyTo), title });
    i = j + 1;
  }

  return results;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

const AUTOGEN_HEADER = (notePath: string): string =>
  `-- AUTOGENERATED FROM ${notePath} — DO NOT EDIT BY HAND\n`;
const CELL_BEGIN = (i: number): string => `-- @cell ${i} begin\n`;
const CELL_END = (i: number): string => `-- @cell ${i} end\n`;

/**
 * Compute the `.lean` mirror path for a note.
 *
 * @param notePath  Absolute path to the .md file.
 * @param notesRoot Absolute path to the notes root directory.
 */
export function leanPathForNote(notePath: string, notesRoot: string): string {
  const root = notesRoot.endsWith("/") ? notesRoot : notesRoot + "/";
  const rel = notePath.startsWith(root) ? notePath.slice(root.length) : notePath;
  const leanRel = rel.endsWith(".md") ? rel.slice(0, -3) + ".lean" : rel + ".lean";
  return root + ".lean/" + leanRel;
}

/**
 * Build the splice descriptor for a note.
 *
 * Returns `null` if the note contains no `lean4` blocks (no .lean file needed,
 * no LSP required).
 */
export function buildLeanSplice(notePath: string, mdText: string, notesRoot: string): LeanSplice | null {
  const raw = scanLean4Blocks(mdText);
  if (raw.length === 0) return null;

  const leanPath = leanPathForNote(notePath, notesRoot);
  const header = AUTOGEN_HEADER(notePath);

  let cursor = header.length;
  const blocks: LeanBlockSlice[] = [];
  const parts: string[] = [header];

  for (let idx = 0; idx < raw.length; idx++) {
    const block = raw[idx];

    const beginMarker = CELL_BEGIN(idx);
    const endMarker = CELL_END(idx);

    const leanFrom = cursor + beginMarker.length;
    const leanTo = leanFrom + block.body.length;

    blocks.push({
      index: idx,
      title: block.title,
      noteBodyFrom: block.bodyFrom,
      noteBodyTo: block.bodyTo,
      leanFrom,
      leanTo,
    });

    parts.push(beginMarker, block.body, endMarker);
    cursor = leanTo + endMarker.length;

    // separate blocks with a blank line (except after last)
    if (idx < raw.length - 1) {
      parts.push("\n");
      cursor += 1;
    }
  }

  return { notePath, leanPath, blocks, leanText: parts.join("") };
}

/**
 * Build a trivial splice for a standalone `.lean` file.
 *
 * The whole file content IS the lean text — no header, no cell markers,
 * and leanPath = notePath (no mirror write needed).
 * The single block maps note offsets 1:1 to lean offsets.
 */
export function buildFullFileLeanSplice(notePath: string, fileText: string): LeanSplice {
  const block: LeanBlockSlice = {
    index: 0,
    title: "",
    noteBodyFrom: 0,
    noteBodyTo: fileText.length,
    leanFrom: 0,
    leanTo: fileText.length,
  };
  return { notePath, leanPath: notePath, blocks: [block], leanText: fileText };
}

// ---------------------------------------------------------------------------
// Offset mapping helpers
// ---------------------------------------------------------------------------

/**
 * Map a character offset in the lean text back to a note offset.
 *
 * Returns `null` if the lean offset falls outside all known block ranges
 * (i.e., it's in an autogen header or cell marker line).
 */
export function leanOffsetToNote(splice: LeanSplice, leanOffset: number): number | null {
  for (const block of splice.blocks) {
    if (leanOffset >= block.leanFrom && leanOffset <= block.leanTo) {
      return block.noteBodyFrom + (leanOffset - block.leanFrom);
    }
  }
  return null;
}

/**
 * Map a note body offset to the corresponding lean text offset.
 *
 * Returns `null` if the note offset is not within any lean4 block body.
 */
export function noteOffsetToLean(splice: LeanSplice, noteOffset: number): number | null {
  for (const block of splice.blocks) {
    if (noteOffset >= block.noteBodyFrom && noteOffset <= block.noteBodyTo) {
      return block.leanFrom + (noteOffset - block.noteBodyFrom);
    }
  }
  return null;
}

/**
 * Find the block that contains the given lean text offset.
 */
export function blockForLeanOffset(splice: LeanSplice, leanOffset: number): LeanBlockSlice | null {
  for (const block of splice.blocks) {
    if (leanOffset >= block.leanFrom && leanOffset <= block.leanTo) return block;
  }
  return null;
}

/**
 * Find the block that contains the given note offset.
 */
export function blockForNoteOffset(splice: LeanSplice, noteOffset: number): LeanBlockSlice | null {
  for (const block of splice.blocks) {
    if (noteOffset >= block.noteBodyFrom && noteOffset <= block.noteBodyTo) return block;
  }
  return null;
}

/**
 * Convert a 0-based (line, character) position in the lean text to an offset.
 */
export function leanPositionToOffset(leanText: string, line: number, character: number): number {
  let remaining = line;
  let offset = 0;
  while (remaining > 0 && offset < leanText.length) {
    if (leanText[offset] === "\n") remaining--;
    offset++;
  }
  return offset + character;
}

/**
 * Convert a lean text offset to a 0-based (line, character) position.
 */
export function leanOffsetToPosition(leanText: string, offset: number): { line: number; character: number } {
  let line = 0;
  let lineStart = 0;
  for (let i = 0; i < offset && i < leanText.length; i++) {
    if (leanText[i] === "\n") {
      line++;
      lineStart = i + 1;
    }
  }
  return { line, character: offset - lineStart };
}
